### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by memboc** [angular/preboot#43]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [x] server side
- [ ] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **What is the current behavior?**
Server side errors when loading page
 ```
 ReferenceError: window is not defined                                                                                
     at EventReplayer.getWindow (/home/ubuntu/myapp/node_modules/preboot/src/browser/event.replayer.ts:31:35)     
     at EventReplayer.replayAll (/home/ubuntu/myapp/node_modules/preboot/src/browser/event.replayer.ts:47:30)     
     at SafeSubscriber._next (/home/ubuntu/myapp/node_modules/preboot/src/browser/browser-preboot.module.ts:24:20)
     at SafeSubscriber.__tryOrUnsub (/home/ubuntu/myapp/node_modules/rxjs/src/Subscriber.ts:254:10)               
     at SafeSubscriber.next (/home/ubuntu/myapp/node_modules/rxjs/src/Subscriber.ts:204:14)                       
     at Subscriber._next (/home/ubuntu/myapp/node_modules/rxjs/src/Subscriber.ts:135:22)                          
     at Subscriber.next (/home/ubuntu/myapp/node_modules/rxjs/src/Subscriber.ts:95:12)                            
     at FirstSubscriber._emitFinal (/home/ubuntu/myapp/node_modules/rxjs/src/operator/first.ts:157:19)            
     at FirstSubscriber._emit (/home/ubuntu/myapp/node_modules/rxjs/src/operator/first.ts:139:10)                 
     at FirstSubscriber._next (/home/ubuntu/myapp/node_modules/rxjs/src/operator/first.ts:117:12)   
```

* **If the current behavior is a bug, please provide the steps to reproduce** 

angular universal following this guide https://github.com/Gorniv/universal/tree/cli

app.server.module.ts
```
import { NgModule } from '@angular/core';
import { ServerModule } from '@angular/platform-server';
import { AppModule } from './app.module';
import { AppComponent } from './components/app.component';
import {ServerPrebootModule} from "preboot/src/server/server-preboot.module";
import {BrowserModule} from "@angular/platform-browser";

@NgModule({
  imports: [
    BrowserModule.withServerTransition({ appId: 'uniapp' }),
    ServerModule,
    AppModule,
    ServerPrebootModule.recordEvents({ appRoot: 'app-root' })
  ],
  bootstrap: [AppComponent]
})
export class AppServerModule { }
```

app.module.ts
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './components/app.component';
import { HomeComponent } from './components/home/home.component';
import { FilterPipe } from './pipes/filter.pipe';
import { DataService } from './services/data.service';
import { HttpModule } from '@angular/http';
import { LayoutService } from './services/layout.service';
import { SanitizeHtmlPipe } from './pipes/sanitize-html.pipe';
import { AppRoutingModule } from './app-routing.module';
import { Subject } from 'rxjs/Subject';
import { FormsModule } from '@angular/forms';
import { ApiService } from './services/api.service';
import {BrowserPrebootModule} from "preboot/src/browser/browser-preboot.module";

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    FilterPipe,
    SanitizeHtmlPipe,
 ],
  imports: [
    BrowserModule,
    HttpModule,
    AppRoutingModule,
    FormsModule,
    BrowserPrebootModule.replayEvents()
  ],
  providers: [
    DataService,
    ApiService,
    LayoutService,
    Subject,
  ],
  bootstrap: [AppComponent],
})
export class AppModule {
}

```

* **Please tell us about your environment:**
- Angular: 4.4.3
- preboot: 5.0.0

- Browser:  Google Chrome 61.0.3163.100 
- Language: TypeScript 2.3.3
- OS: Windows | Linux
- Platform: NodeJs 8.5.0

**Comment by jeffwhelpley** [comment]
So, by your stack trace you are running replayEvents() on the server side which is causing the error. Where is your main.ts for the server? I suspect that somehow you are pointing your serve side entry point to the browser module instead of the server module.

**Comment by CaerusKaru** [comment]
@jeffwhelpley is right. You need to create two separate App{EntryPoint}Module's, one for the browser and one for the server, both of which import `AppModule`. This way you can make sure your `preboot` imports are in the right place (otherwise the server ends up importing the Browser preboot module, causing the error above).

**Comment by jeffwhelpley** [comment]
@CaerusKaru @memboc I just realized that more than likely the issue is that in the server module you are importing everything from the browser module. That unfortunately will not work with preboot. You do need to have two completely separate modules. I will think about a way to fix this, though, so other people don't run into the same issue.

**Comment by jeffwhelpley** [comment]
FYI, check out `5.1.4`. I added a fix so that you can include the browser module with the server module and it won't break things anymore.
