### ISSUE TITLE
webpack fails at importing preboot/browser

### ISSUE THREAD

**Issue by TitanNano** [angular/preboot#53]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [X] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [X] client side
- [ ] inline
- [X] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
We get the following error from ts-loder:

> Module build failed: Error: Typescript emitted no output for /Users/jeremy/Documents/workspace/zmbSSR/node_modules/preboot/browser.ts.
> You should not need to recompile .ts files in node_modules.
> Please contact the package author to advise them to use --declaration --outDir.
> More https://github.com/Microsoft/TypeScript/issues/12358
>     at successLoader (/Users/jeremy/Documents/workspace/zmbSSR/node_modules/ts-loader/dist/index.js:47:15)
>     at Object.loader (/Users/jeremy/Documents/workspace/zmbSSR/node_modules/ts-loader/dist/index.js:29:12)
>  @ ./build/app/app.ts 16:16-42
>  @ ./build/app/app.ngfactory.ts
>  @ ./build/app/app.browser.ts

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Webpack needs to be configured to load typescript files:
```JavaScript
resolve: {
    extensions: ['.ts', '.js']
},
module: {
    loaders: [
        { test: /\.ts$/, loader: 'awesome-typescript-loader' }
    ]
},
```

* **What is the expected behavior?**
no typescript files should be provided inside the published node module.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Browser: all
- Language: TypeScript
- OS:  Mac OS X
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by TitanNano** [comment]
dupe of https://github.com/angular/preboot/issues/41
